# Generated by Django 6.0.6 on 2026-06-15 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idEmpleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=150)),
                ('departamento', models.CharField(db_column='departamento', max_length=150)),
                ('sueldo', models.DecimalField(db_column='sueldo', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'empleado',
            },
        ),
    ]
